# Project 2: Exploratory Data Analysis (EDA) Report
---
## Assigned Topic:
__[Startup Investments]__

## Selected Problem Statement: 
__[Approach: Optimal Funding Trajectories for Follow-On Investment
Problem Statement: A venture capital firm struggles to reliably select seed-stage startups that will eventually secure follow-on funding, resulting in a portfolio of stalled companies. The Investment Analytics team needs to analyze historical funding data across industry categories, funding round counts, time between rounds, and geographic regions to identify the patterns most strongly associated with startups that successfully raise additional capital. Uncovering these historical trajectories will allow the firm to accurately refine its $10M seed-stage investment criteria and target startups with the highest odds of advancing.]__

## 1. Introduction & Objectives
*(Guidelines: Introduce your topic and give a brief high-level overview of the industry or topic you are exploring so a non-technical audience understands the context.)*

### 1.1 Context & Background
Venture capital companies invest in startup firms even before they become profitable. In the seed round, a small amount invested to the startups to prove their ideas. This is just the begining, the to grow, startups go to the market and rise follow-on rounds, each round is multible investors, checking the firm and deciding the worth, that is must be more than before. If the startup firm did the seed stage only and no more rounds, that means its stopped or stuck, and mostly no return or profit.

The portfolio of the venture capital firm is now full of stalled companies, and a $10M to invest in startups who in seed stage, but with not just guissing. The question is: What kind of seed-stage startups have istorically gone on to raise again?

Using Crunchbase data, records of companies worldwide, company's industry, location, date etc... we will answer that question.

### 1.2 Core Analytical Objectives
*(List the key targeted questions that will guide your analysis to solve the chosen problem statement. Use bullet points.)*

The client invests in seed-stage startups, so our analysis focus on companies raised seed round, and measure of sccess is if the company went to at least additional round.

* 1_ What % of all seed-stage startups raised again? (Baseline - Benchmark)
* 2_ What markets or industries produce seed-stage firms that excced the baseline? (Industry category)
* 3_ Is the region/country effects the odd of raising again? (Geographic region)
* 4_ How many rounds startup firms usually do? and does a 2nd round predict the eventual outcome (closed, operating...) of the company? (Round counts)
* 5_ How long between the round for the startups that do advance? How long it takes before deciding an investment in stalled. (Time between rounds)
* 6_ As recommendation, what screening criteria the firm shoud do to the $10M? and how well these criteria did an improment.

## 2. Environment Setup & Data Collection
*(Rubric Checkpoint: Ensure all modules are imported cleanly with appropriate standard aliases. Data files must be loaded using relative paths for replicability.)*

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# To make it full display for all the columns
pd.set_option('display.max_columns', None)

# To make all upcoming graphs consist
sns.set_style('whitegrid')

In [6]:
# Load data using strictly relative file paths
startups = pd.read_csv('../data/startup_investments.csv', encoding = 'latin-1')
# The latin-1 fix the error by using default read_csv

In [15]:
# To confirm the loading
startups.head(2)

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,undisclosed,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,"17,50,000",acquired,USA,NY,New York City,New York,1.0,2012-06-01,2012-06,2012-Q2,2012.0,2012-06-30,2012-06-30,1750000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"40,00,000",operating,USA,CA,Los Angeles,Los Angeles,2.0,NaN,NaN,NaN,NaN,2010-06-04,2010-09-23,0.0,4000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
# To check the shpae, number of firms(rows) and columns(attribute) of each firm.
startups.shape

(54294, 39)

---
## 3. Data Handling

* Before cleaning, we will point structural problems, null values, or wrong data types.

In [17]:
# Initial assessment: Check shapes, null values, and summary data types

In [19]:
startups.info()
# The dates columns are stored as str, also the funding_total_usd is as str.
# Many columns non-null count is exactly 49438 out of 54294

<class 'pandas.DataFrame'>
RangeIndex: 54294 entries, 0 to 54293
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   permalink             49438 non-null  str
 1   name                  49437 non-null  str
 2   homepage_url          45989 non-null  str
 3   category_list         45477 non-null  str
 4    market               45470 non-null  str
 5    funding_total_usd    49438 non-null  str
 6   status                48124 non-null  str
 7   country_code          44165 non-null  str
 8   state_code            30161 non-null  str
 9   region                44165 non-null  str
 10  city                  43322 non-null  str
 11  funding_rounds        49438 non-null  float64
 12  founded_at            38554 non-null  str
 13  founded_month         38482 non-null  str
 14  founded_quarter       38482 non-null  str
 15  founded_year          38482 non-null  float64
 16  first_funding_at      49438 non-null  str
 17  last_funding_at       49438 non-null  str
 18  seed                  49438 non-null  float64
 19  venture               49438 non-null  float64
 20  equity_crowdfunding   49438 non-null  float64
 21  undisclosed           49438 non-null  float64
 22  convertible_note      49438 non-null  float64
 23  debt_financing        49438 non-null  float64
 24  angel                 49438 non-null  float64
 25  grant                 49438 non-null  float64
 26  private_equity        49438 non-null  float64
 27  post_ipo_equity       49438 non-null  float64
 28  post_ipo_debt         49438 non-null  float64
 29  secondary_market      49438 non-null  float64
 30  product_crowdfunding  49438 non-null  float64
 31  round_A               49438 non-null  float64
 32  round_B               49438 non-null  float64
 33  round_C               49438 non-null  float64
 34  round_D               49438 non-null  float64
 35  round_E               49438 non-null  float64
 36  round_F               49438 non-null  float64
 37  round_G               49438 non-null  float64
 38  round_H               49438 non-null  float64
dtypes: float64(23), str(16)
memory usage: 24.5 MB

In [24]:
startups.columns.to_list() #The  ' market ',' funding_total_usd ' columns both have literal spaces

['permalink',
 'name',
 'homepage_url',
 'category_list',
 ' market ',
 ' funding_total_usd ',
 'status',
 'country_code',
 'state_code',
 'region',
 'city',
 'funding_rounds',
 'founded_at',
 'founded_month',
 'founded_quarter',
 'founded_year',
 'first_funding_at',
 'last_funding_at',
 'seed',
 'venture',
 'equity_crowdfunding',
 'undisclosed',
 'convertible_note',
 'debt_financing',
 'angel',
 'grant',
 'private_equity',
 'post_ipo_equity',
 'post_ipo_debt',
 'secondary_market',
 'product_crowdfunding',
 'round_A',
 'round_B',
 'round_C',
 'round_D',
 'round_E',
 'round_F',
 'round_G',
 'round_H']

In [30]:
# Percentage of missing values in each column
(startups.isnull().mean()*100).sort_values(ascending = False)

state_code              44.448742
founded_quarter         29.122923
founded_month           29.122923
founded_year            29.122923
founded_at              28.990312
city                    20.208494
region                  18.655837
country_code            18.655837
 market                 16.252256
category_list           16.239363
homepage_url            15.296350
status                  11.364055
name                     8.945740
 funding_total_usd       8.943898
permalink                8.943898
funding_rounds           8.943898
first_funding_at         8.943898
last_funding_at          8.943898
seed                     8.943898
venture                  8.943898
equity_crowdfunding      8.943898
undisclosed              8.943898
convertible_note         8.943898
debt_financing           8.943898
angel                    8.943898
grant                    8.943898
private_equity           8.943898
post_ipo_equity          8.943898
post_ipo_debt            8.943898
secondary_market         8.943898
product_crowdfunding     8.943898
round_A                  8.943898
round_B                  8.943898
round_C                  8.943898
round_D                  8.943898
round_E                  8.943898
round_F                  8.943898
round_G                  8.943898
round_H                  8.943898
dtype: float64

In [34]:
# Many columns share the same % of missing values (8.94%)
# that means the same whole rows are missing from all columns

# To check number of rows where all columns are missing:
startups.isnull().all(axis = 1).sum()

np.int64(4856)

In [37]:
# To check some of fully empty rows
startups[startups.isnull().all(axis = 1)].head(2)

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,seed,venture,equity_crowdfunding,undisclosed,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
49438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
# To check number of duplicated row
startups.duplicated().sum()
# The number is same as the null rows (1st original and 4855 duplicates)
# So, its the same problem, removing the nulls will eliminate the duplicates

np.int64(4855)

In [43]:
# To check what the values in the (funding_total_usd) looks loke, as they are stored as str
startups[' funding_total_usd '].head(3)
# we can see that numbers are seperated by ',', and the '-' means (no disclosed fundings),
# and also it seems ther are some spaces in it too.

0     17,50,000
1     40,00,000
2        40,000
Name:  funding_total_usd , dtype: str

In [46]:
# Now lets check the values in (Market), are there spaces as the column name is?
startups[' market '].head(3).to_list()
# And the answer is YES there are spaces for some reason.

[' News ', ' Games ', ' Publishing ']

In [47]:
# summary statistics for numeric values
startups.describe()
# We can notice that funding rounds  median is 1 and max is 18 (positive skewed)
# most companies do one round only.
# Also, the founded_year starts from 1902 till 2014. 
# Finally, the funding_total_usd is missing because the data stored as str.

,funding_rounds,founded_year,seed,venture,equity_crowdfunding,undisclosed,convertible_note,debt_financing,angel,grant,private_equity,post_ipo_equity,post_ipo_debt,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
count,49438.000000,38482.000000,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04
mean,1.696205,2007.359129,2.173215e+05,7.501051e+06,6.163322e+03,1.302213e+05,2.336410e+04,1.888157e+06,6.541898e+04,1.628453e+05,2.074286e+06,6.088736e+05,4.434360e+05,3.845592e+04,7.074227e+03,1.243955e+06,1.492891e+06,1.205356e+06,7.375261e+05,3.424682e+05,1.697692e+05,5.767067e+04,1.423197e+04
std,1.294213,7.579203,1.056985e+06,2.847112e+07,1.999048e+05,2.981404e+06,1.432046e+06,1.382046e+08,6.582908e+05,5.612088e+06,3.167231e+07,2.678348e+07,3.428169e+07,3.864461e+06,4.282166e+05,5.531974e+06,7.472704e+06,7.993592e+06,9.815218e+06,5.406915e+06,6.277905e+06,5.252312e+06,2.716865e+06
min,1.000000,1902.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.000000,2006.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.000000,2010.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.000000,2012.000000,2.500000e+04,5.000000e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,18.000000,2014.000000,1.300000e+08,2.351000e+09,2.500000e+07,2.924328e+08,3.000000e+08,3.007950e+10,6.359026e+07,7.505000e+08,3.500000e+09,4.700000e+09,5.800000e+09,6.806116e+08,7.200000e+07,3.190000e+08,5.420000e+08,4.900000e+08,1.200000e+09,4.000000e+08,1.060000e+09,1.000000e+09,6.000000e+08

In [ ]:
# Data cleaning operations (handling data types, text styling, missing values, etc.)

---
## 4. Exploratory Data Analysis (EDA)
*(Rubric Checkpoint: Demonstrate mastery of basic descriptive statistics, sorting records, and applying Boolean masking techniques to isolate specific baseline metrics.)*

### 4.1. ----

In [ ]:
# Compute appropriate summary statistics

### 4.2. ----

In [ ]:
# Target Analysis Block 1:

### 4.3. ----

In [ ]:
# Visualization 1

**Visualization 1 Interpretation:**
> *Write 2-3 sentences explaining exactly what relationship or pattern this chart demonstrates and how it addresses your project objectives.*

In [ ]:
# Visualization 2

**Visualization 2 Interpretation:**
> *Write 2-3 sentences explaining exactly what relationship or pattern this chart demonstrates and how it addresses your project objectives.*

---
## 5. Summary of Findings & Actionable Recommendations
*(Guidelines: Connect individual observations into a cohesive narrative that guides the target non-technical audience toward data-driven actions.)*

### 5.1 Key Insights (Summary of Findings)
*(Use bullet points to highlight the core truths revealed by your analysis)*
* ...
* ...

### 5.2 Actionable Recommendations
*(Translate your data into clear choices or recommendations for your stakeholder based directly on the problem statement)*
* ...
* ...

### 5.3 Limitations & Areas for Further Research
* ...

---

## 6. Data Dictionary & References

### 6.1 Data Dictionary
| Feature / Column | Data Type | Source | Description |
|:---|:---|:---|:---|
| column_name_1 | type | Original / Engineered | Detailed explanation of what this variable represents |
| column_name_2 | type | Original / Engineered | Detailed explanation of what this variable represents |

### 6.2 References & Sources
* *Source 1:*